const state = {
  meta: null,
  groups: [],
  selected: new Set(),
  groupDataCache: new Map(),
  lastOutput: "",
  lastFilename: "iplist.txt",
};

const els = {
  updatedAt: document.getElementById("updatedAt"),
  statusText: document.getElementById("statusText"),
  errorBox: document.getElementById("errorBox"),
  searchInput: document.getElementById("searchInput"),
  dataType: document.getElementById("dataType"),
  formatType: document.getElementById("formatType"),
  plainOverride: document.getElementById("plainOverride"),
  groupsList: document.getElementById("groupsList"),
  visibleCount: document.getElementById("visibleCount"),
  resultCount: document.getElementById("resultCount"),
  previewOutput: document.getElementById("previewOutput"),
  statGroups: document.getElementById("statGroups"),
  statDomains: document.getElementById("statDomains"),
  statIpv4: document.getElementById("statIpv4"),
  statCidr: document.getElementById("statCidr"),
  selectAllBtn: document.getElementById("selectAllBtn"),
  clearAllBtn: document.getElementById("clearAllBtn"),
  previewBtn: document.getElementById("previewBtn"),
  copyBtn: document.getElementById("copyBtn"),
  downloadBtn: document.getElementById("downloadBtn"),
};

function setStatus(text, bad = false) {
  els.statusText.textContent = text;
  els.statusText.classList.toggle("bad", bad);
  els.statusText.classList.toggle("ok", !bad);
}

function showError(message) {
  els.errorBox.textContent = message;
  els.errorBox.classList.remove("hidden");
  setStatus("ошибка", true);
}

function hideError() {
  els.errorBox.classList.add("hidden");
  els.errorBox.textContent = "";
}

async function fetchJson(path) {
  const response = await fetch(path, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`${path}: HTTP ${response.status}`);
  }
  return response.json();
}

function normalizeLines(items) {
  return [...new Set((items || []).filter(Boolean).map(String))].sort();
}

function routeLineFromCidr(cidr) {
  const [ip, prefixRaw] = cidr.split("/");
  const prefix = Number(prefixRaw || "32");
  const parts = ip.split(".").map(Number);

  if (parts.length !== 4 || parts.some((part) => Number.isNaN(part)) || Number.isNaN(prefix)) {
    return null;
  }

  const maskNum = prefix === 0 ? 0 : (0xffffffff << (32 - prefix)) >>> 0;
  const mask = [24, 16, 8, 0].map((shift) => (maskNum >>> shift) & 255).join(".");
  return `route add ${ip} mask ${mask} 0.0.0.0`;
}

function makeKeeneticBat(cidrs, groupLabel = "selected") {
  const updated = state.meta?.updated_at || new Date().toISOString();
  const lines = [
    "REM Generated by IP List Builder",
    `REM Updated: ${updated}`,
    `REM Group: ${groupLabel}`,
    ...cidrs.map(routeLineFromCidr).filter(Boolean),
  ];
  return `${lines.join("\r\n")}\r\n`;
}

function formatResult(dataType, formatType, plainOverride, items) {
  if (plainOverride || formatType === "plain") {
    return `${items.join("\n")}${items.length ? "\n" : ""}`;
  }

  if (formatType === "json") {
    return `${JSON.stringify({
      updated_at: state.meta?.updated_at || null,
      type: dataType,
      groups: [...state.selected].sort(),
      count: items.length,
      items,
    }, null, 2)}\n`;
  }

  if (formatType === "keenetic") {
    return makeKeeneticBat(items, [...state.selected].sort().join(",") || "selected");
  }

  return `${items.join("\n")}\n`;
}

function filenameFor(dataType, formatType, plainOverride) {
  if (!plainOverride && formatType === "json") return "iplist.json";
  if (!plainOverride && formatType === "keenetic") return "iplist-keenetic.bat";
  if (dataType === "domains") return "iplist-domains.txt";
  if (dataType === "ipv4") return "iplist-ipv4.txt";
  return "iplist-cidr.txt";
}

async function loadGroupData(groupId) {
  if (!state.groupDataCache.has(groupId)) {
    const data = await fetchJson(`generated/groups/${groupId}/data.json`);
    state.groupDataCache.set(groupId, data);
  }
  return state.groupDataCache.get(groupId);
}

async function collectSelectedData() {
  const selectedIds = [...state.selected].sort();
  const selectedData = await Promise.all(selectedIds.map(loadGroupData));
  const domains = normalizeLines(selectedData.flatMap((group) => group.domains || []));
  const ipv4 = normalizeLines(selectedData.flatMap((group) => group.ipv4 || []));
  const cidr = normalizeLines(selectedData.flatMap((group) => group.cidr || []));
  return { domains, ipv4, cidr };
}

async function buildOutput() {
  hideError();
  const selected = await collectSelectedData();
  let dataType = els.dataType.value;
  const formatType = els.formatType.value;
  const plainOverride = els.plainOverride.checked;

  if (formatType === "keenetic") {
    dataType = "cidr";
    els.dataType.value = "cidr";
  }

  const items = selected[dataType] || [];
  const output = formatResult(dataType, formatType, plainOverride, items);
  const filename = filenameFor(dataType, formatType, plainOverride);
  state.lastOutput = output;
  state.lastFilename = filename;
  els.resultCount.textContent = `${items.length} строк`;
  return { output, filename, items };
}

function renderGroups() {
  const query = els.searchInput.value.trim().toLowerCase();
  const filtered = state.groups.filter((group) => {
    const haystack = `${group.id} ${group.title} ${group.description}`.toLowerCase();
    return haystack.includes(query);
  });

  els.visibleCount.textContent = `${filtered.length} / ${state.groups.length}`;
  els.groupsList.innerHTML = filtered.map((group) => `
    <article class="group-card">
      <label class="group-title">
        <input type="checkbox" data-group-id="${group.id}" ${state.selected.has(group.id) ? "checked" : ""}>
        <span>${group.title}</span>
      </label>
      <p>${group.description || ""}</p>
      <div class="group-stats">
        <span class="pill">id: ${group.id}</span>
        <span class="pill">domains: ${group.domains ?? 0}</span>
        <span class="pill">ipv4: ${group.ipv4 ?? 0}</span>
        <span class="pill">cidr: ${group.cidr ?? 0}</span>
        ${group.unresolved ? `<span class="pill">unresolved: ${group.unresolved}</span>` : ""}
      </div>
    </article>
  `).join("");

  els.groupsList.querySelectorAll("input[type='checkbox']").forEach((input) => {
    input.addEventListener("change", () => {
      if (input.checked) state.selected.add(input.dataset.groupId);
      else state.selected.delete(input.dataset.groupId);
      updateStatsFromMeta();
    });
  });
}

function updateStatsFromMeta() {
  const selectedGroups = state.groups.filter((group) => state.selected.has(group.id));
  els.statGroups.textContent = selectedGroups.length;
  els.statDomains.textContent = selectedGroups.reduce((sum, group) => sum + (group.domains || 0), 0);
  els.statIpv4.textContent = selectedGroups.reduce((sum, group) => sum + (group.ipv4 || 0), 0);
  els.statCidr.textContent = selectedGroups.reduce((sum, group) => sum + (group.cidr || 0), 0);
}

async function preview() {
  try {
    const { output } = await buildOutput();
    els.previewOutput.textContent = output || "Пустой результат.";
  } catch (error) {
    showError(`Не удалось собрать предпросмотр: ${error.message}`);
  }
}

async function copyOutput() {
  try {
    const { output } = await buildOutput();
    await navigator.clipboard.writeText(output);
    setStatus("скопировано");
  } catch (error) {
    showError(`Не удалось скопировать: ${error.message}`);
  }
}

async function downloadOutput() {
  try {
    const { output, filename } = await buildOutput();
    const blob = new Blob([output], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  } catch (error) {
    showError(`Не удалось скачать файл: ${error.message}`);
  }
}

async function init() {
  try {
    state.meta = await fetchJson("generated/meta.json");
    state.groups = state.meta.groups || [];
    els.updatedAt.textContent = state.meta.updated_at || "неизвестно";
    setStatus("готово");
    renderGroups();
    updateStatsFromMeta();
  } catch (error) {
    els.updatedAt.textContent = "нет данных";
    showError("Списки ещё не сгенерированы. Запустите GitHub Actions update-lists.");
    console.error(error);
  }
}

els.searchInput.addEventListener("input", renderGroups);
els.formatType.addEventListener("change", () => {
  if (els.formatType.value === "keenetic") {
    els.dataType.value = "cidr";
  }
});
els.selectAllBtn.addEventListener("click", () => {
  state.groups.forEach((group) => state.selected.add(group.id));
  renderGroups();
  updateStatsFromMeta();
});
els.clearAllBtn.addEventListener("click", () => {
  state.selected.clear();
  renderGroups();
  updateStatsFromMeta();
});
els.previewBtn.addEventListener("click", preview);
els.copyBtn.addEventListener("click", copyOutput);
els.downloadBtn.addEventListener("click", downloadOutput);

init();
