#!/usr/bin/env python3
from __future__ import annotations

import ipaddress
import json
import os
import socket
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import dns.exception
    import dns.resolver
except Exception:  # pragma: no cover
    dns = None  # type: ignore

ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILE = ROOT / "sources" / "services.json"
GENERATED_DIR = ROOT / "generated"
GROUPS_DIR = GENERATED_DIR / "groups"
ALL_DIR = GENERATED_DIR / "all"

DNS_TIMEOUT = float(os.getenv("DNS_TIMEOUT", "3"))
DNS_LIFETIME = float(os.getenv("DNS_LIFETIME", "5"))


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def normalize_domain(domain: str) -> str:
    return domain.strip().lower().rstrip(".")


def unique_sorted(items: list[str]) -> list[str]:
    return sorted(set(x.strip() for x in items if x and x.strip()))


def is_tld_entry(domain: str) -> bool:
    return domain.startswith(".")


def resolve_a_dnspython(domain: str) -> list[str]:
    if dns is None:  # type: ignore[truthy-function]
        return []

    resolver = dns.resolver.Resolver()  # type: ignore[attr-defined]
    resolver.timeout = DNS_TIMEOUT
    resolver.lifetime = DNS_LIFETIME
    answers = resolver.resolve(domain, "A")
    return [answer.to_text() for answer in answers]


def resolve_a_socket(domain: str) -> list[str]:
    old_timeout = socket.getdefaulttimeout()
    socket.setdefaulttimeout(DNS_LIFETIME)
    try:
        records = socket.getaddrinfo(domain, None, socket.AF_INET, socket.SOCK_STREAM)
        return [record[4][0] for record in records]
    finally:
        socket.setdefaulttimeout(old_timeout)


def resolve_ipv4(domain: str) -> tuple[list[str], str | None]:
    try:
        ips = resolve_a_dnspython(domain)
    except Exception as exc:
        dnspython_error = f"{type(exc).__name__}: {exc}"
        try:
            ips = resolve_a_socket(domain)
        except Exception as fallback_exc:
            return [], f"{dnspython_error}; fallback {type(fallback_exc).__name__}: {fallback_exc}"

    valid_ips: list[str] = []
    for ip in ips:
        try:
            valid_ips.append(str(ipaddress.IPv4Address(ip)))
        except ipaddress.AddressValueError:
            continue

    if not valid_ips:
        return [], "no A records"
    return unique_sorted(valid_ips), None


def collapse_ipv4_to_cidr(ipv4_list: list[str]) -> list[str]:
    addresses = [ipaddress.IPv4Network(f"{ip}/32") for ip in unique_sorted(ipv4_list)]
    return [str(network) for network in ipaddress.collapse_addresses(addresses)]


def cidr_to_keenetic_route(cidr: str) -> str:
    network = ipaddress.IPv4Network(cidr, strict=False)
    return f"route add {network.network_address} mask {network.netmask} 0.0.0.0"


def make_keenetic_bat(cidrs: list[str], group_id: str, updated_at: str) -> str:
    lines = [
        "REM Generated by IP List Builder",
        f"REM Updated: {updated_at}",
        f"REM Group: {group_id}",
    ]
    lines.extend(cidr_to_keenetic_route(cidr) for cidr in cidrs)
    return "\r\n".join(lines) + "\r\n"


def write_text(path: Path, lines_or_text: list[str] | str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(lines_or_text, list):
        text = "\n".join(lines_or_text) + ("\n" if lines_or_text else "")
    else:
        text = lines_or_text
    path.write_text(text, encoding="utf-8", newline="")


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def load_services() -> dict[str, Any]:
    return json.loads(SOURCE_FILE.read_text(encoding="utf-8"))


def generate_group(group: dict[str, Any], updated_at: str) -> dict[str, Any]:
    group_id = group["id"]
    original_domains = group.get("domains", [])
    domains = unique_sorted([normalize_domain(domain) for domain in original_domains])

    ipv4_by_domain: dict[str, list[str]] = {}
    unresolved: dict[str, str] = {}
    all_ipv4: list[str] = []

    for domain in domains:
        if is_tld_entry(domain):
            continue
        ips, error = resolve_ipv4(domain)
        if error:
            unresolved[domain] = error
        if ips:
            ipv4_by_domain[domain] = ips
            all_ipv4.extend(ips)

    ipv4 = unique_sorted(all_ipv4)
    cidr = collapse_ipv4_to_cidr(ipv4)

    data = {
        "id": group_id,
        "title": group.get("title", group_id),
        "description": group.get("description", ""),
        "updated_at": updated_at,
        "domains": domains,
        "ipv4": ipv4,
        "ipv6": [],
        "cidr": cidr,
        "ipv4_by_domain": ipv4_by_domain,
        "unresolved": unresolved,
        "stats": {
            "domains": len(domains),
            "ipv4": len(ipv4),
            "cidr": len(cidr),
            "unresolved": len(unresolved),
        },
    }

    target_dir = GROUPS_DIR / group_id
    write_text(target_dir / "domains.txt", domains)
    write_text(target_dir / "ipv4.txt", ipv4)
    write_text(target_dir / "cidr.txt", cidr)
    write_text(target_dir / "keenetic.bat", make_keenetic_bat(cidr, group_id, updated_at))
    write_json(target_dir / "data.json", data)
    return data


def main() -> None:
    services = load_services()
    updated_at = now_iso()

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GROUPS_DIR.mkdir(parents=True, exist_ok=True)
    ALL_DIR.mkdir(parents=True, exist_ok=True)

    group_results = [generate_group(group, updated_at) for group in services.get("groups", [])]

    all_domains = unique_sorted([domain for result in group_results for domain in result["domains"]])
    all_ipv4 = unique_sorted([ip for result in group_results for ip in result["ipv4"]])
    all_cidr = collapse_ipv4_to_cidr(all_ipv4)
    unresolved = {
        result["id"]: result["unresolved"]
        for result in group_results
        if result.get("unresolved")
    }

    all_data = {
        "id": "all",
        "title": "All groups",
        "description": "Combined generated data for all groups",
        "updated_at": updated_at,
        "domains": all_domains,
        "ipv4": all_ipv4,
        "ipv6": [],
        "cidr": all_cidr,
        "unresolved": unresolved,
        "groups": [result["id"] for result in group_results],
        "stats": {
            "domains": len(all_domains),
            "ipv4": len(all_ipv4),
            "cidr": len(all_cidr),
            "unresolved": sum(len(result.get("unresolved", {})) for result in group_results),
        },
    }

    write_text(ALL_DIR / "domains.txt", all_domains)
    write_text(ALL_DIR / "ipv4.txt", all_ipv4)
    write_text(ALL_DIR / "cidr.txt", all_cidr)
    write_text(ALL_DIR / "keenetic.bat", make_keenetic_bat(all_cidr, "all", updated_at))
    write_json(ALL_DIR / "data.json", all_data)

    meta = {
        "updated_at": updated_at,
        "generator": "scripts/generate.py",
        "safe_mode": True,
        "groups": [
            {
                "id": result["id"],
                "title": result["title"],
                "description": result["description"],
                "domains": result["stats"]["domains"],
                "ipv4": result["stats"]["ipv4"],
                "cidr": result["stats"]["cidr"],
                "unresolved": result["stats"]["unresolved"],
            }
            for result in group_results
        ],
        "all": all_data["stats"],
    }
    write_json(GENERATED_DIR / "meta.json", meta)


if __name__ == "__main__":
    main()
